<?php
/**
 *
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 * Create by: Limberg Alcon 09 2020
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo and "Supercharged by SuiteCRM" logo. If the display of the logos is not
 * reasonably feasible for  technical reasons, the Appropriate Legal Notices must
 * display the words  "Powered by SugarCRM" and "Supercharged by SuiteCRM".
 */



// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array (
  0 => 
  array (
   'acceptable_sugar_versions' =>  array (
        'regex_matches' => array(
            '.*',
        ),
    ),
    'acceptable_sugar_flavors' => array(
        'CE',
    ),
  ),
  'readme' => 'Here we allow Administrators to create business logic for field calculations without needing to write PHP code. You can select calculated field and create the formula that is automatically updated based on calculation you provide.',
  'key' => 'tac',
  'author' => 'TechEsperto Solutions LLC, Limberg Alcon',
  'description' => 'New theme for Limberg Alcon',
  'is_uninstallable' => true,
  'name' => 'TechBlue',
  'published_date' => '2018-02-2 13:15:25',
  'type' => 'module',
  'version' => 1513235725,
  'remove_tables' => 'prompt',
);


$installdefs = array (
  'id' => 'techBlue',
  'beans' => 
  array (
	0 => 
    array (
      'module' => 'tech_blue',
      'class' => 'tech_blue',
      'path' => 'modules/tech_blue/tech_blue.php',
      'tab' => false,
    ),
  ),
  'layoutdefs' => 
  array (
  ),
  'relationships' => 
  array (
  ),
 
  'copy' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/custom/include/Dashlets',
      'to' => 'custom/include/Dashlets',
    ),
    1 => 
    array (
      'from' => '<basepath>/TechBlue',
      'to' => 'themes/TechBlue',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/modules/tech_blue',
      'to' => 'modules/tech_blue',
    ),
    
  ),
  
  'post_install'=>
    array (
      0 => '<basepath>/scripts/post_install.php',
      
    ),
    'pre_uninstall'=>
    array (
      0 => '<basepath>/scripts/pre_uninstall.php',
      
     ),
	
);
